apiVersion: apps/v1
kind: Deployment
metadata:
  name: learn-k8s-backend
  labels:
    app: learn-k8s-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learn-k8s-backend
  template:
    metadata:
      labels:
        app: learn-k8s-backend
    spec:
      containers:
      - name: learn-k8s-backend
        image: kittinan/learn-k8s:backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: learn-k8s-backend-config

