apiVersion: v1
kind: Service
metadata:
  name: learn-k8s-frontend
  labels:
    app: learn-k8s-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30180
    protocol: TCP
    name: http
  selector:
    app: learn-k8s-frontend
